<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>nat</string>
	</array>
	<key>name</key>
	<string>Natural</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#wrong</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#trailing-space</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#comments</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#data-definition</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#subroutine</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#hash-vars</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#keywords</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#operators</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#numbers</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#strings</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#punctuation</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#system-vars</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#variable-modifier</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>comments</key>
		<dict>
			<key>match</key>
			<string>(^\*.*$|\/\*.*$)</string>
			<key>name</key>
			<string>comment.natural</string>
		</dict>
		<key>data-definition</key>
		<dict>
			<key>begin</key>
			<string>(?i:define\s+data)</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>keyword.natural</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?i:end-define)</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>keyword.natural</string>
				</dict>
			</dict>
			<key>name</key>
			<string>data.definition.natural</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#data-definition-keywords</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#external-storage-area</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#variable-modifier</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#variable-type</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#view-definition</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#numbers</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#strings</string>
				</dict>
			</array>
		</dict>
		<key>data-definition-keywords</key>
		<dict>
			<key>match</key>
			<string>\b(?i:with|view|value|result|redefine|parameter|optional|of|object|local|init|independent|global|dynamic|context|constant|const|by)</string>
			<key>name</key>
			<string>keyword.natural</string>
		</dict>
		<key>external-storage-area</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.definition.natural</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.natural</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?i:(using)\s+([a-z0-9]+))</string>
			<key>name</key>
			<string>storage.definition.using.natural</string>
		</dict>
		<key>hash-vars</key>
		<dict>
			<key>match</key>
			<string>\#[a-zA-Z0-9-]+</string>
			<key>name</key>
			<string>variable.natural</string>
		</dict>
		<key>keywords</key>
		<dict>
			<key>match</key>
			<string>\b(?i:callnat|define|subroutine|fetch|end-define|end-decide|end-routine|end-norec|if|then|else|end-if|find number|find|end-find|reset|add|to|decide|on|first|value|of|with|display|write|input|read|work|file|set|ignore|escape|module|thru|no|records|found|routine|specified|none|top|bottom|true|false|perform|end)\b</string>
			<key>name</key>
			<string>keyword.natural</string>
		</dict>
		<key>numbers</key>
		<dict>
			<key>match</key>
			<string>[0-9]+[,.]?[0-9]*</string>
			<key>name</key>
			<string>constant.numeric.natural</string>
		</dict>
		<key>operators</key>
		<dict>
			<key>match</key>
			<string>\b(?i:eq|ne|lt|le|gt|ge|and|or|not)\b</string>
			<key>name</key>
			<string>keyword.operator.natural</string>
		</dict>
		<key>strings</key>
		<dict>
			<key>applyEndPatternLast</key>
			<integer>1</integer>
			<key>begin</key>
			<string>\'</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.natural</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\'</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.natural</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.natural</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string></string>
					<key>name</key>
					<string>constant.character.escape.apostrophe.natural</string>
				</dict>
			</array>
		</dict>
		<key>subroutine</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.natural</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?&lt;=subroutine)\s+([a-z0-9\-]+)</string>
			<key>name</key>
			<string>definition.subroutine.natural</string>
		</dict>
		<key>system-vars</key>
		<dict>
			<key>match</key>
			<string>(?i:\*(winmgrvers|winmgr|window-ps|window-pos|window-ls|username|user|ui|ubound|type|tpvers|tpsys|tp|timx|timn|timestmp|timeout|time|timd|this-object|subroutine|steplib|startup|server-type|screenio|rowcount|program|pid|pf-name|pf-key|patch-level|parse-type|parse-row|pars-namespace-uri|parse-level|parse-col|parm-user|pagesize|page-number|pagelevel|page-event|osvers|os|opsys|occurrence|number|net-user|natvers|machineclass|log-ps|log-ls|locale|linesize|line-count|line|library-id|level|length|lbound|language|isn|init-user|init-program|initid|hostname|hardware|hardcopy|group|etid|error-ta|error-nr|error-line|devicedatx|datvs|datv|datu|datn|datj|dati|datg|date|datd|data|dat4u|dat4j|dat4i|da4e|dat4d|cursor|curs-line|curs-field|curs-col|current-unit|cputime|counter|convid|com|codepage|browser-io|applic-name|applic-id))</string>
			<key>name</key>
			<string>constant.language</string>
		</dict>
		<key>trailing-space</key>
		<dict>
			<key>match</key>
			<string>[ \t]+$</string>
			<key>name</key>
			<string>invalid.deprecated.trailing-whitespace</string>
		</dict>
		<key>variable-level</key>
		<dict>
			<key>match</key>
			<string>^\s*[0-9]+</string>
			<key>name</key>
			<string>constant.numeric.level.natural</string>
		</dict>
		<key>variable-modifier</key>
		<dict>
			<key>match</key>
			<string>(?&lt;=\()(?i:em|hd|pm|ad|al)=[^\)]+</string>
			<key>name</key>
			<string>variable.parameter.natural</string>
		</dict>
		<key>variable-type</key>
		<dict>
			<key>match</key>
			<string>(?&lt;=\()(?i:[abnpu][0-9]+|i[148]|f[48]|[cdlt])</string>
			<key>name</key>
			<string>entity.name.class.natural</string>
		</dict>
		<key>view-definition</key>
		<dict>
			<key>match</key>
			<string>([a-zA-Z0-9\-]+)(?=\s+view)</string>
			<key>name</key>
			<string>definition.view.natural</string>
		</dict>
		<key>wrong</key>
		<dict>
			<key>match</key>
			<string>\t</string>
			<key>name</key>
			<string>invalid</string>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.natural</string>
	<key>uuid</key>
	<string>2d1c1e4a-c6cd-41c5-91b8-3e65e2ef5be9</string>
</dict>
</plist>
